# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec85b65eaadd4120caf6d82655fb268868312301de51302d9c882e652bf1fe4e016524dacebc5a482eacb15e45f9a5fa80a3745b754e1c557016fd64a0d29dcc

test:
  secret_key_base: e94ecbf57066de7b1b8d61ecc65c392679c27550936fefe0359ecaee18fffee4a3e7c7f0ac3556795a59e43c0cecc950b53def916c9f7830cdfad8750493ca80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
